### ISSUE TITLE
Doped-AGNR 

### ISSUE THREAD

**Issue by mlorenznano** [dipc-cc/hubbard#95]
Hello @tfrederiksen and @sofiasanz ,

This is probably not an issue with the code but with my knowledge/skill.
So I want to calculate different properties of doped-AGNR. and there I encountered a problem. If I have the following structure I find the shown spin-polarization for the ground-state:

![image](https://user-images.githubusercontent.com/82454407/118515407-a7206580-b735-11eb-939a-7b5801d06cdd.png)

The problem is that I hindered the system to go in the actual groundstate for a periodically-doped chain which looks like this:

![image](https://user-images.githubusercontent.com/82454407/118513315-e483f380-b733-11eb-8940-b75c7685a32b.png)

And this geometry unfortunately produces a completely different bandstructure. 
Can I define the unitcell in such a way that I reproduce the bandstructure obtained for the first structure (In theory they are the same)?

**Comment by sofiasanz** [comment]
Hi @mlorenznano if I understood it correctly the second image is the geometry of the top figure tiled by two along the periodicity axis, no?

I guess that the groundstate for this system is to have antiferromagnetically coupled defects in the chain as you show in the bottom image. It looks like in order to do that one has to tile the geometry of the top geometry (single unit cell) twice to have each defect with contrary spin alignments. I don't think you can recover the solution in the second figure without tiling your geometry, because if you try the polarization of the second image on the first geometry (ferromagnetically aligned) you would end up with a chain of ferromagnetically aligned defects, and that's not what you want.

**Comment by mlorenznano** [comment]
Yes you summed it up perfectly. Picture one can't reproduce the AFM chain. The problem for me is that the bandstructure of the first structure is really close to the one of previous DFT calculations. The bandstructure of the second structure however is completely different.

**Comment by sofiasanz** [comment]
Which polarization did you obtain with the DFT calculation?
And also, are you comparing the bandstructure of the single cell (first image) with the structure composed by two cells (second image)? Because they have different sizes, so the Brilloun zone is different for each of them.

**Comment by mlorenznano** [comment]
> Which polarization did you obtain with the DFT calculation?

I don't know. I didn't do the DFT-calculations (they're from a master thesis).  

> And also, are you comparing the bandstructure of the single cell (first image) with the structure composed by two cells (second image)? Because they have different sizes, so the Brilloun zone is different for each of them.

upps. I'm sorry. In fact I think the bandstructure is almost the same (certainly good enough for me). 

I will check my results again. Thank you :)

**Comment by mlorenznano** [comment]
Okay so I combined two neighboring bands from the second structure to form one band and I was able to produce nice results (and watched out for bands which cross each other).
Thanks again :)
